
services:
  # Servidor Web Nginx para el Backend
  nginx:
    image: nginx:alpine
    container_name: estoyok-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - estoyok-network

  # PHP-FPM para Laravel
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: estoyok-backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - estoyok-network
    depends_on:
      - postgres
      - redis

  # Laravel Queue Worker
  worker:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: estoyok-worker
    command: php artisan queue:work
    user: "www-data"
    volumes:
      - ./backend:/var/www/html
    networks:
      - estoyok-network
    depends_on:
      - postgres
      - redis
      - backend

  # Laravel Scheduler
  scheduler:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: estoyok-scheduler
    command: php artisan schedule:work
    user: "www-data"
    volumes:
      - ./backend:/var/www/html
    networks:
      - estoyok-network
    depends_on:
      - postgres
      - redis
      - backend

  # Base de Datos Geoespacial
  postgres:
    image: postgis/postgis:16-3.4
    container_name: estoyok-postgres
    environment:
      POSTGRES_DB: estoyok_db
      POSTGRES_USER: estoyok_user
      POSTGRES_PASSWORD: estoyok_password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - estoyok-network

  # Cache y Colas de Laravel
  redis:
    image: redis:alpine
    container_name: estoyok-redis
    ports:
      - "6379:6379"
    networks:
      - estoyok-network

  # Frontend Web (Next.js)
  frontend:
    build:
      context: ./frontend-web
      dockerfile: ../docker/node/Dockerfile
    container_name: estoyok-frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    networks:
      - estoyok-network
    depends_on:
      - backend

  # Mailpit para pruebas de email
  mailpit:
    image: axllent/mailpit
    container_name: estoyok-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - estoyok-network

networks:
  estoyok-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
